import { c as create_ssr_component, v as validate_component, b as add_attribute } from "../../../chunks/ssr.js";
import { N as NavbarGuest } from "../../../chunks/NavbarGuest.js";
import "../../../chunks/firebase.client.js";
import "firebase/auth";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: `.webpage.svelte-vgf8jd{height:100vh;overflow:hidden;background:linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab, #23a6d5, #e73c7e, #ee7752);background-size:400% 400%;animation:svelte-vgf8jd-gradient 30s infinite ease}.containerMain.svelte-vgf8jd{text-align:center;margin:0;padding:10px;width:100%}.title.svelte-vgf8jd{font-size:4vmin;margin-top:30vh;margin-bottom:3vh;font-family:"Mulish", sans-serif;color:white}.box.svelte-vgf8jd{border:2px dashed white;width:30vw;height:40vh;left:35vw;top:23vh;position:fixed;border-radius:2vh;pointer-events:none}label.svelte-vgf8jd{display:block;justify-content:center;margin-top:1vh;margin-bottom:1vh}input.svelte-vgf8jd{padding:1vh;width:30vmin;border-radius:5px;border:white solid 1px;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;height:4vmin}input.svelte-vgf8jd:focus{outline-color:rgb(0, 22, 135);outline-style:double;outline-width:1px}.submitButton.svelte-vgf8jd{margin-top:1vh;background-color:transparent;border:rgb(255, 255, 255) solid 1px;color:rgb(255, 255, 255);padding:1vmin;list-style-type:none;font-size:2vmin;cursor:pointer;border-radius:5px;transition-duration:0.4s;font-family:'Mulish', sans-serif}.submitButton.svelte-vgf8jd:hover{background-color:rgb(255, 255, 255);color:rgb(85, 85, 85);box-shadow:0 0 3vh rgba(255, 255, 255, .5)}p.svelte-vgf8jd{margin-top:2vh;display:inline;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;color:white;font-size:1.6vmin}a.svelte-vgf8jd{margin-top:2vh;display:inline-block;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;text-decoration:none;font-size:1.6vmin}@keyframes svelte-vgf8jd-gradient{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}`,
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let email = "";
  $$result.css.add(css);
  return `<link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet"> <link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200..1000;1,200..1000&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet"> <title data-svelte-h="svelte-o1os5">PowerBoard</title> ${validate_component(NavbarGuest, "NavbarGuest").$$render($$result, {}, {}, {})} <div class="webpage svelte-vgf8jd"><div class="box svelte-vgf8jd"></div> <div class="containerMain svelte-vgf8jd"><h1 class="title svelte-vgf8jd" data-svelte-h="svelte-q8xqlv">Forgot Password</h1> <form><label class="svelte-vgf8jd"><input type="email" placeholder="Email" class="svelte-vgf8jd"${add_attribute("value", email, 0)}></label> <button class="submitButton svelte-vgf8jd" data-svelte-h="svelte-hcajsf">Send Password Reset Email</button></form> <p class="svelte-vgf8jd" data-svelte-h="svelte-qd51yb">Don&#39;t have an account?</p> <a href="/signup" class="svelte-vgf8jd" data-svelte-h="svelte-5zrbmn">Sign Up</a></div> </div>`;
});
export {
  Page as default
};
